
analyzer:
  errors:
    dead_code: ignore
    depend_on_referenced_packages: ignore
    equal_elements_in_set: ignore
    must_be_immutable: ignore
    unused_element_parameter: ignore
include: package:flutter_lints/flutter.yaml

linter:

  rules:

