name: health
description: "Health app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  lean_requester:
    git:
      url: https://github.com/Jewelch/lean_requester
      ref: v1.1
  
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.0.0
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/    
    - assets/json/
    - assets/fonts/

#= Flutter Launcher Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dexter_logo.png"
  min_sdk_android: 26
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/dexter_logo.png"
    background_color: "#000000"
    theme_color: "#000000"

#= Flutter Native Splash
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/dexter_splash_logo.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/dexter_splash_logo.png
    color: "#FFFFFF"
  web: true
    